### ISSUE TITLE
RFC: Hass.io UI

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/home-assistant-polymer#1710]
## Add-on install
- Show security rating as badge
- Show badge for network/full_access/homeassistant_api/hassio_api/docker_api/host_pid
- Show install button only on supported platforms. (use `available` flag)

## Add-on page
- Show security rating as badge
- Show red warning banner if the protection mode is disabled
- Allow to disable the protection mode
- Add support for stats to see the current resource

## Add-on store
- Gray out Add-on they not match arch/machine (use `available` flag)

## Snapshot
- Add support for upload (need change on component)

**Comment by balloob** [comment]
add-on store: I think the backend needs to filter these unless we want to have an option that can tell a user: you don't have access to these add-ons as they don't work on your machine.

Snapshot: this requires signed urls to be implemented: https://github.com/home-assistant/home-assistant/issues/16745

**Comment by balloob** [comment]
This check should compare versions correctly: https://github.com/home-assistant/home-assistant-polymer/blob/ee6bd93577e689f9875852e776d66cda849aedf6/hassio/src/dashboard/hassio-hass-update.js#L77-L79

**Comment by frenck** [comment]
@balloob Both options are valid for hiding the add-ons or showing them disabled. Disabled, would raise questions, but so are add-ons that are not showing at all.

Maybe graying them out would actually be possible, you could even leave the add-on detail page in place. And show a warning on the detailed page(as a persistent bar or when a user tries to install it).

---

### Some nice to haves IMHO:

Replace the ugly puzzle pieces with the actual icon (not logo) of the add-on. Since it is now an indicator if the add-on is running or not, it could be replaced with a simple green/gray dot in the top left of the card or even by a switch to toggle (comparable to the frontend). This would make addons more recognizable and would be more like "others" do. The icon is already available in the API, and at least all community add-ons provide both an icon and a logo.

---
A lot of people seem to use the auto-update of add-ons. A question I often get asked: "What changed?".  Currently, the changelog button only shows when the add-on has an update pending. For a user who has auto-updates, there is no way to view the changelog again. Could the "CHANGELOG" button be shown alway?

I might be a little too much with all features that are rolling in, but maybe making the version number clickable?

---
Replace the add-on / hassio supervisor logs text cards with something that looks like:

Example of how GitLab shows output from a build:
https://gitlab.com/hassio-addons/addon-node-red/-/jobs/74390658

Example of how Travis shows output from a build:
https://travis-ci.org/home-assistant/home-assistant/jobs/394350068

I'm not talking about streaming logs (that would require much much more work, but making them readable would definitely help.

**Comment by tjorim** [comment]
Another nice to have, but getting more important with each new add-on:
searching the add-on store for a specific add-on.

**Comment by pvizeli** [comment]
I close the issue, because it's now to old

**Comment by balloob** [comment]
I disagree that it's too old, as I don't think that we fixed any of these things. This is still on my radar.

**Comment by dogmatic69** [comment]
Previous ticket home-assistant/home-assistant-polymer#1441 for adding upload for backups was closed in favour of this one. Now this one is closed but still not resolved. 

Was reopened and then closed with the commit `Fixes #1710 (except the upload snapshot)` so should still be open or a third ticket for the upload?

**Comment by bramkragten** [comment]
Please create a new issue for that.
