### ISSUE TITLE
Input Number Missing Value Text (non-LL)

### ISSUE THREAD

**Issue by mynameisdaniel32** [home-assistant/home-assistant-polymer#1755]
**Home Assistant release with the issue:**
0.79.3 -> 0.80.0b5

**Last working Home Assistant release (if known):**
0.78.X

**Browser and Operating System:**
Browsers (on Windows 10):
Opera 56.0.3051.43
Chrome 69.0.3497.100
Firefox 62.0.3
Multiple Home Assistant installation methods affected (venv on Debian for me)

**Description of problem:**
For input number (box and slider) the actual value is missing. See https://github.com/home-assistant/home-assistant/issues/16957 for more examples/info. This doesn't seem to be affecting Lovelace. Column width does not affect this, even with columns as wide as they go, the numbers do not display.

![image](https://user-images.githubusercontent.com/24840952/46924725-ec0c2900-d06e-11e8-8ff4-4994384640ea.png)

![image](https://user-images.githubusercontent.com/24840952/46772701-d4683400-cd40-11e8-89de-efefea0d80ee.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by balloob** [comment]
it shows/hides depending on the width of the card

**Comment by pplucky** [comment]
> it shows/hides depending on the width of the card

Issue 1: Slider labels seem to have disappeared for all cards... Any way of forcing to always appear?

Issue 2: Boxes don't appear at all

How it should appear:
![image](https://user-images.githubusercontent.com/16407309/46838163-f220b200-cdaf-11e8-898e-535ed0d918a2.png)

How it appears:
![image](https://user-images.githubusercontent.com/16407309/46838152-e634f000-cdaf-11e8-92c6-6bae7190713f.png)

**Comment by balloob** [comment]
Please fill in browser in issue template.

Forcing showing it will not happen.

**Comment by pplucky** [comment]
@balloob: but isn’t it strange that it worked perfectly (label visible) before updating and it doesn’t anymore after? Is this a new “functionality”?

**Comment by yunnanpl** [comment]
I have the same issue, and it seems that it was mentioned in numerous places:
https://github.com/home-assistant/home-assistant/issues/9779
https://github.com/home-assistant/home-assistant/issues/16957
and here.

I did some digging, and it seems that I solved the issue. I posted the answer here:
https://github.com/home-assistant/home-assistant/issues/9779#issuecomment-429120685

**Comment by mynameisdaniel32** [comment]
I've updated the original post with browser details and to show that this occurs even with columns at their native width.

**Comment by mynameisdaniel32** [comment]
This is still an issue as of 0.81.0b2 😢

**Comment by iantrich** [comment]
This should be resolved in final 0.81: https://github.com/home-assistant/home-assistant-polymer/pull/1861

**Comment by perozonp** [comment]
Should? I just upgraded to 0.81 and I still have this issue (Lovelace is not having it).

**Comment by perozonp** [comment]
Not sure what happened, probably caching. My phone is ok now, input_numbers look fine. Thanks!

**Comment by Martin73Mac** [comment]
Still present on Android Chrome and native Android application.
