### ISSUE TITLE
Heavy lag when using slider to change temperature

### ISSUE THREAD

**Issue by jottr** [home-assistant/home-assistant-polymer#198]
```
Chrome 55.0.2883.91
Android 7.1.1 Nexus 6P
```
When trying to set change the target temperature via slider I witness heavy lag.
This only happens when using the slider on the actual Android device. I can't reproduce this behaviour on Chrome for desktop. 
I tried debugging the issue on the device with devtools [remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/) feature.

A captured the slider lag in the devtools timeline: 

<img width="1145" alt="screen" src="https://cloud.githubusercontent.com/assets/2744198/22717819/8469484c-ed9d-11e6-93a0-87b78753fd8b.png">

Note the FPS of 4.
I'll be happy to provide more info if needed to help debug this issue.

**Comment by andrey-git** [comment]
@jottr Does this happen with any other type of slider? (light dimmer, input_slider)

**Comment by jottr** [comment]
This is the only slider I have currently set up.

**Comment by sdague** [comment]
Fwiw, we just merged a new control for the thermostat which uses up / down buttons instead of the slider into polymer master. It would be interesting to know that after you have that if the lag is still there (i.e. something about the whole system), or if it's gone (which means paper-slider was the culprit).

![screenshot_349](https://cloud.githubusercontent.com/assets/14367/23020023/0610df24-f413-11e6-8470-0505c10a5df9.png)

**Comment by jottr** [comment]
Thanks @sdague for the heads-up! 
I won't be able to check for a few weeks since I'm currently not at the place being automated. 
Issue can be closed for now, I'll reopen if the issue remains then.

**Comment by jottr** [comment]
So, I've updated HASS to the most recent version. The lag still persists even with the up/down buttons.
