### ISSUE TITLE
Xiaomi Binary sensor displaying incorrect state in 0.84.2

### ISSUE THREAD

**Issue by aidbish** [home-assistant/home-assistant-polymer#2326]
**Home Assistant release with the issue:** 
0.84.2
Frontend JavaScript version: latest

**Last working Home Assistant release (if known):**
0.83

**Browser and Operating System:**

**Description of problem:**
Xiaomi binary door/window sensors now display state as on/off instead of open/close periodically. If rebooting, they sometimes show correctly only after a while they revert to on/off. Have customized entities to the correct devices classes to see if it fixes the issue but still happens

No errors are shown in the logs

**Comment by iantrich** [comment]
Fixed by https://github.com/home-assistant/home-assistant-polymer/pull/2293
Should be in next beta

**Comment by aidbish** [comment]
Hi. I have just updated to 84.3 and issue is still there
The sensor now consistently display on or off. even though i have device class specified to window or door and they have open/close
