### ISSUE TITLE
detached dropdown on input_select in Tile

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/home-assistant-polymer#27815]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

in default theme:

![Image](https://github.com/user-attachments/assets/b226cbd1-4e6a-44b7-a389-c20558361e31)

![Image](https://github.com/user-attachments/assets/33072a68-8f1b-4b93-ba2e-3818f6285df2)

### Describe the behavior you expected

drop down not getting lost, and living on its own

### Steps to reproduce the issue

1. use yaml below
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.11.0b4

### In which browser are you experiencing the issue?

any

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
  - type: tile
    features:
      - type: select-options
    features_position: inline
    entity: input_select.woongedeelte_areas
    hide_state: true
    tap_action:
      action: none
    icon_tap_action:
      action: none
```
and 
```
type: vertical-stack
cards:
  - type: heading
    heading: Themes selectie
    heading_style: title

  - entity: input_select.theme
    <<: &select
      type: tile
      features:
        - type: select-options
      features_position: inline
      hide_state: true
      vertical: false

  - entity: input_select.kiosk_theme
    name: Kiosk
    <<: *select
  - entity: input_select.full_house_theme
    name: Full house
    <<: *select
  - entity: input_select.dev_theme
    name: Develop
    <<: *select
  - entity: input_select.alarm_theme
    name: Alarm
    <<: *select
  - entity: input_select.sunrise_theme
    name: Sunrise
    <<: *select
  - entity: input_select.sunset_theme
    name: Sunset
    <<: *select

```
### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

https://github.com/home-assistant/frontend/issues/27724#event-20615242180

was merged, but didnt fix?

**Comment by wendevlin** [comment]
Should be fixed with:
- #29350

**Comment by Mariusthvdb** [comment]
still happening in HA 2026.2.1

could this be re-opened?

![Image](https://github.com/user-attachments/assets/585d2a8c-4455-4e91-bcac-abd8cf7ba44b)

**Comment by wendevlin** [comment]
> could this be re-opened?

It's just merged in dev branch for now. Will be released in march.

**Comment by Mariusthvdb** [comment]
a ok thx... was too anxious, apologies ;)
