### ISSUE TITLE
Add a card: a "search" field is automatically filled with my login

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/home-assistant-polymer#28237]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

2026.1.0.dev0
20251029.0
(in fact, I see this for many months)

In a dev environment (localhost:8123), I very often see this:
when I select "Add a new card", my HA login is automatically inputted into a "search" field:

<img width="660" height="428" alt="Image" src="https://github.com/user-attachments/assets/2c08137a-46a8-4657-a57b-c63896c14b6d" />

This only happens with that "localhost" access in Chrome (never with other HA test setups which are not on "localhost").
A browser cache is purged very often.
I do not observe this in FF 145.02 (both in a normal & private window).

### Describe the behavior you expected

Nothing is automatically inputted.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2026.1.0.dev0

### In which browser are you experiencing the issue?

Chrome 142.0.7444.176 

### Which operating system are you using to run this browser?

Win10x64

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

**Comment by silamon** [comment]
Also list the browser extensions you have for password management, since most likely one browser extension is filling that in there.

**Comment by ildar170975** [comment]
No browser extensions in chrome. 
Only Ignore X-Frame headers 2.0.0 to make webpages working in iframe.

**Comment by uptimeZERO** [comment]
Hi @ildar170975!

Thank you very much for bringing this to our attention, and for being a member of the Home Assistant community! 😁 

I spent some time investigating the issue and have discovered that this has been resolved in a previous PR https://github.com/home-assistant/frontend/issues/27963.

As such, I will be closing off this issue as it has already been resolved 😄 

Thanks again for contributing to the community, I hope you have a wonderful day! 🌞

**Comment by ildar170975** [comment]
I noticed this glitch on a dev version with all merged PRs. So, it probably included your mentioned PR, right? Then why the glitch is still there?

**Comment by ildar170975** [comment]
Can anyone reopen this please?
Still see it in devcontainer for dev branch.

**Comment by karwosts** [comment]
I've seen this sometimes too and when I looked into it I came away thinking maybe there's not really a whole lot we can do about it. 

I believe what happens here is that browser developers, being fed up with websites that try to disable login autofill (for "security"?), just decided that going forward they are just going to ignore autofill instructions from website developers and just rely on their own internal heuristics to decide what is or is not a login field. So no matter how we setup this form, if some secret browser algorithm decides that this kind of smells like it might be a username field, it will apply this autofill logic, no matter what we try to do. There is autofill controls in the html spec, but the major browser developers just decided that they prefer to ignore them 😕 .

**Comment by ildar170975** [comment]
But why I only see this with a localhost? Could it related somehow?

**Comment by nevada750club** [comment]
Sorry but I also encounter this problem remotely from the nabu.casa cloud.

**Comment by nevada750club** [comment]
I noticed that if I remove the `autocomplete='off'` directive in the `<input>` tag, the field seems to work correctly without defaulting to LogIn.
Can you try applying this change?

**Comment by ildar170975** [comment]
> if I remove the `autocomplete='off'` directive in the `<input>` tag, the field seems to work correctly without defaulting to LogIn.

No, do not see it helps unfortunately.

**Comment by MPatzek** [comment]
I have the same problem persisting already pretty long. Now I did not forgot to look for a solution and found this thread. I am using the google password manager in chrome and it autofills my normal HA login username everytime. I use a reverse proxy over a tld and not an localhost or ip address.

I can also confirm that removing `autocomplete='off'` from the input tag helps. Since it is disabled anyway, why not simply remove it?

any way to fix this permanently in the code?

**Comment by ildar170975** [comment]
up

**Comment by jelzo** [comment]
I have the same issue. Chromium (Chrome and Edge) always autofills the field with my username and therefore no cards are shown.

It occurs because Chromium (Chrome and Edge) thinks the field is a username field (there is a nearby slot[name=password-toggle-button] element) and therefore forces the autocomplete. 

Replacing `autocomplete="off"` with `autocomplete="search"` should fix the issue and should not cause problems elsewhere.

Related:
https://issues.chromium.org/issues/40093420
