### ISSUE TITLE
Input_select dropdown detached when resizing screenwidth

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/home-assistant-polymer#28473]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

![Image](https://github.com/user-attachments/assets/4e3b7859-8d05-4b13-955f-6157b248c3c4)

### Describe the behavior you expected

dropdown remaining connected to the input_select under all circumstances

### Steps to reproduce the issue

1. just dropdown and resize
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.12.x

### In which browser are you experiencing the issue?

any

### Which operating system are you using to run this browser?

macOS

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

**Comment by Mariusthvdb** [comment]
found this one too, notice the screen getting narrow and the dropdown being cut-off

![Image](https://github.com/user-attachments/assets/bba436d1-0e71-4173-bfba-e6701b0d4d9b)

**Comment by dnestico** [comment]
It's not just input_selects but basically all dropdowns, here it happens for the effects button in more-info on lights, desktop only mobile is fine. 

<img width="1188" height="1624" alt="Image" src="https://github.com/user-attachments/assets/b0c91058-18e9-46e0-8bf0-064156f738de" />

**Comment by Mariusthvdb** [comment]
most of what I reported has been fixed, so can I close @dnestico ?

**Comment by dnestico** [comment]
Damn so I just checked and all drop downs seem to be fixed except for the old ones are still broken, like HACS redownload drop down hasn't been updated to new one so that's still broken. Guess you can close this then. 
![Screenshot_20260312-122403.png](https://github.com/user-attachments/assets/5c64f471-bd47-448c-8b08-a8943ae68487)
