### ISSUE TITLE
Mobile Chrome (Android): two lines for values

### ISSUE THREAD

**Issue by Molodax** [home-assistant/home-assistant-polymer#327]
Hi,

After the latest mobile Chrome (Android) update to v. 5.0.3071.125 , there is an issue with appearance of values for different items. They are split in two lines.
The issue was with HASS v. 47.1 and it is the same in 48.0. It appears normal (values and units of measurement are on the same line) just after loading the page, however, the split (as on the screenshot) becomes apparent after you navigate between tabs.
It can be fixed by refreshing the page until you change a tab again.

![screenshot_20170702-135556](https://user-images.githubusercontent.com/22867988/27830309-22d47308-60c6-11e7-8209-84ff844bdcdb.png)

**Comment by NovapaX** [comment]
fixed with #932

**Comment by Molodax** [comment]
@novapaX, please re-open it because the issue still persists in 0.65

**Comment by NovapaX** [comment]
For what sensor? Please provide a screenshot and the state of that sensor.

**Comment by Molodax** [comment]
I must admit that after update from 65.0 to 65.2, there was a significant improvement, however, the issue still appears time time.
![screenshot_20180313-231111](https://user-images.githubusercontent.com/22867988/37372841-862f8478-2714-11e8-9ab1-e5648afd46c5.png)

**Comment by balloob** [comment]
Sensors without a unit of measurement will still be wrapped in two lines as we don't know how to keep them together as we don't know how to interpret the value. This is not fixable.

**Comment by Molodax** [comment]
@balloob it looks quite ugly, isn't?
Maybe it would be better to keep the issue open so someone else could find a solution.
"Not fixable" sounds a bit flat.

![screenshot_20180314-080807](https://user-images.githubusercontent.com/22867988/37388049-3811170c-275f-11e8-8beb-2704a3e2ce41.png)

**Comment by NovapaX** [comment]
Agree that this should not happen with such short states.

The problem is that I can't reproduce. 
I created a 'copy' of that Date & Time sensor using a template sensor, but I have to make the screen a lot more narrow to make the state wrap like that. (that's desktop chrome in responsive design mode)

Can you share a copy of your configuration for those 'time to sleep' blocks/components?

**Comment by Molodax** [comment]
Hi @NovapaX 
Here is my configuration:

configuration.yaml

```
input_datetime:
  alarmtime:
    name: Wake-up Time
    icon: mdi:timer
    has_date: false
    has_time: true
    initial: '07:00'
  sleeptime:
    name: Sleep Time
    icon: mdi:timer
    has_date: false
    has_time: true
    initial: '22:30'
```

group.yaml

```
Alarmclock:
  name: Wake Me Up
  control: hidden
  icon: mdi:briefcase
  entities:
    - group.alarmclock
    - input_datetime.alarmtime
    - automation.wakeup_time
Sleepclock:
  name: Time To Sleep
  control: hidden
  icon: mdi:sleep
  entities:
    - group.sleepclock
    - input_datetime.sleeptime
    - automation.nightbed_time
```
