### ISSUE TITLE
Config Entity Options deCONZ

### ISSUE THREAD

**Issue by bastshoes** [home-assistant/home-assistant-polymer#3554]
**Home Assistant release with the issue:**

0.98.1
**Last working Home Assistant release (if known):**
unknown
**UI (States or Lovelace UI?):**

![image](https://user-images.githubusercontent.com/22978694/64065564-b84ed900-cc17-11e9-8560-52c6ad78562b.png)

**Browser and Operating System:**

FireFox 68.0.2 (64-bit) on Windows7
**Description of problem:**

Config Entity Options for deCONZ integration shows only check boxes (no labels)

![image](https://user-images.githubusercontent.com/22978694/64065609-1e3b6080-cc18-11e9-9110-ee84ae30044c.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by springstan** [comment]
Could you check if the text is just hidden or maybe displayed in white?

**Comment by balloob** [comment]
Fixed in 98.1

**Comment by bastshoes** [comment]
I'm running 0.98.1.

**Comment by KennethLavrsen** [comment]
This issue was reported for 0.98.1. Why do you close it @balloob 
A similar issue was closed for the unifi integration but it is still broken for deconz

**Comment by aidbish** [comment]
Probably means 98.2

**Comment by bastshoes** [comment]
Just updated to 0.98.2. Issue still exiist.

**Comment by KennethLavrsen** [comment]
I also updated. And I made sure that the browser cache is refreshed. Issue is till there

![image](https://user-images.githubusercontent.com/8373419/64118759-903ab380-cd98-11e9-87dd-b88495cecf42.png)

**Comment by balloob** [comment]
@Kane610 I think that strings.json should not contain `async_step_deconz_devices` but instead be `deconz_devices` ? https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/deconz/.translations/en.json#L46

**Comment by Kane610** [comment]
doh! good catch @balloob
