### ISSUE TITLE
UI broken in certain browsers

### ISSUE THREAD

**Issue by raccettura** [home-assistant/home-assistant-polymer#397]
Since 0.51 I've noticed the header (including group tabs) and left menu will work, however the content of the page will be empty. After some digging around I've been able to narrow it down to being an issue in "Firefox Focus" and "fully Kiosk Browser". Something these browsers do seems to be the problem. Chrome, Silk, and Firefox are functional.

Cache was cleared, browser was re-installed. So I don't think it's anything client side.

**Comment by andrey-git** [comment]
It is broken in FF focus but works in regular mobile FF? Weird, are not those essentially the same browser?

**Comment by evaryont** [comment]
Firefox Focus, on both Android and iOS, is a wrapper around the internal Webkit browser. It does have a build option to use the Gecko rendering engine but IIRC, it does not work at the moment. Add on top of that, the various privacy stuff Focus does, but I don't think it blocks anything in HA.

**Comment by raccettura** [comment]
Yea, I think the constant is embedded Android Webkit. What I can't find so far is a way to do some debugging via a console or something. So hoping someone with more knowledge of the frontend and the recent changes has some ideas on how to diagnose this further and find a fix?

I miss my tablet dashboard :'(

**Comment by andrey-git** [comment]
I just tried Fully on Android and it works fine.

If it doesn't work for someone - which Android version are you using?

Also what is the advantage of using Fully over Chrome?

**Comment by raccettura** [comment]
I'm using a Kindle Fire with 5.4. something and installed Fully via the Play Store along with Android System WebView.

**Comment by raccettura** [comment]
Last night I tried restoring the Fire so it was clean. At this point I think it's something with WebKit on Kindle.

Reason for Fully is that it's full screen with some nice remote management features.  I tried HomeDash, but can't seem to get it to run at all.

**Comment by balloob** [comment]
We need to see the errors printed in the JavaScript console to be able to debug this.

**Comment by raccettura** [comment]
After some debugging today:
1. There are no JS console errors.
2. Remove the views and badges show up. So it's got something to do with groups. Cards work when you select one.
3. `<home-assistant-main/>` has nothing but  shadow root in it... the websocket to get data is working. This looks like a rendering issue.

**Comment by raccettura** [comment]
So it looks like this was fixed by https://github.com/home-assistant/home-assistant/pull/9438

**Comment by sresam89** [comment]
I have the latest android chrome, in my phone the webpage still does not render

**Comment by dvbit** [comment]
I think I have this same issue. 0.85 all browsers
