### ISSUE TITLE
NaN JSON values break loading the frontend

### ISSUE THREAD

**Issue by Heronimonimo** [home-assistant/home-assistant-polymer#4191]
**Home Assistant release with the issue:**

0.101.3

**Last working Home Assistant release (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**

Hassio
**Integration:**

https://www.home-assistant.io/integrations/integration/

**Description of problem:**
When the integration sensor spits out an NaN value the frontend won't load and hangs on "Loading data". In the logs it shows the error:
"Unable to serialize to JSON: Out of range float values are not JSON compliant"

After removing the specific statistics sensor the frontend the problem was resolved. It seems to be closely related to home-assistant/home-assistant#20715

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
  - platform: statistics
    entity_id: sensor.gas_usage
    name: gas_stats
    max_age:
      hours: 24          
    sampling_size: 1000
```

**Traceback (if applicable):**
```

```

**Additional information:**

**Comment by bramkragten** [comment]
The solution to the problem is also in the issue you referenced, could you try that and maybe create a PR?

**Comment by Svellem** [comment]
Hi,
I am seing the same error, the only difference being it throws an error listing 600+ different entity states which makes it a bit harder to do a workaround on an entity level. The error comes with the first logon on the frontend after HA is restarted. Any suggestions on where to troubleshoot would be much appreciated. Running Hassio generic installer on Intel NUC (Ubuntu w/docker).

**Comment by Heronimonimo** [comment]
@bramkragten Not sure if fixing for every different sensor is the best way forward. Isn't there a way to make a generic fix that automatically solves this issues for all different sensors?

@Svellem In my case one invalid sensor reading that was than used as input for the statistics sensor caused it. You might try purging your database (https://www.home-assistant.io/integrations/recorder/) and look if the problem still persists. Did you make any changes recently that you know of that might have caused it?

**Comment by bramkragten** [comment]
No, the source of the problem should be addressed and that is integrations reporting `NaN` in their state/attributes. That is not allowed, so every integration that does that should be fixed.

On a higher level we wouldn't know what to do, and the integration should be able to handle a missing value, or set it's state to `unavailable`

**Comment by Svellem** [comment]
@Heronimonimo 
I disabled recorder in my config and deleted the whole database, but the JSON value error is still and prevents me from accessing the frontend.

**This is the start of the log, the rest is a list of 600+ sensors:**

>2019-11-27 19:08:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for zigbee2mqtt_networkmap which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-11-27 19:08:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-11-27 19:08:14 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=1 from 2019-11-27 18:08:05.982943)
2019-11-27 19:08:17 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for floureon which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-11-27 19:08:26 WARNING (MainThread) [homeassistant.setup] Setup of tesla is taking over 10 seconds.
2019-11-27 19:08:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 399, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: sensor.dafang1_light_sensor. Platform mqtt does not generate unique IDs
2019-11-27 19:08:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 399, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: sensor.stueost_temp. Platform mqtt does not generate unique IDs
2019-11-27 19:08:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 399, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: sensor.stueost_humidity. Platform mqtt does not generate unique IDs
2019-11-27 19:08:33 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 399, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: binary_sensor.stueost_motion. Platform mqtt does not generate unique IDs
2019-11-27 19:08:35 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139729363349648] Unable to serialize to JSON: Out of range float values are not JSON compliant
{'id': 8, 'type': 'result', 'success': True, 'result': [<state sun.sun=below_horizon; next_dawn=2019-11-28T06:50:37+00:00, next_dusk=2019-11-28T15:18:45+00:00, next_midnight=2019-11-27T23:04:52+00:00, next_noon=2019-11-28T11:04:41+00:00, next_rising=2019-11-28T07:43:23+00:00, next_setting=2019-11-28T14:25:59+00:00, elevation=-26.21, azimuth=272.43, rising=False, friendly_name=Sun @ 2019-11-27T19:08:16.985996+01:00>, <state zone.home=zoning; hidden=True, latitude=59.43254, longitude=10.63116, radius=100.0, friendly_name=Home @ 2019-11-27T19:08:17.358542+01:00>, <state group.utelys=on; entity_id=('light.inngang', 'switch.vei', 'switch.terrasse'), order=0, friendly_name=Outdoor, assumed_state=True @ 2019-11-27T19:08:30.859159+01:00>, <state scene.ny_scene=scening; entity_id=[], id=1574369729901, friendly_name=Ny scene @ 2019-11-27T19:08:18.273072+01:00>, <state input_boolean.zigbee_permit_join=off; friendly_name=Allow devices to join, icon=mdi:cellphone-wireless @ 2019-11-27T19:08:19.067627+01:00>, <state timer.zigbee_permit_join=idle; duration=0:10:00, remaining=0:10:00, friendly_name=Time remaining @ 2019-11-27T19:08:19.068099+01:00>, <state input_select.zigbee2mqtt_log_level=info; options=['debug', 'info', 'warn', 'error'], friendly_name=Zigbee2mqtt Log Level, icon=mdi:format-list-bulleted @ 2019-11-27T19:08:19.068456+01:00>, <state input_number.vaskemaskin=5.0; initial=None, min=0.0, max=2999.0, step=1.0, mode=box, friendly_name=Vaskemaskin, icon=mdi:washing-machine @ 2019-11-27T19:08:19.068814+01:00>, <state climate.yttergang=unknown; hvac_modes=['auto', 'heat', 'off'], current_temperature=None, min_temp=7.0, max_temp=35.0, temperature=None, preset_mode=None, preset_modes=['none', 'away'], away_setpoint=7, manual_setpoint=7, external_temp=None, room_temp=None, loop_mode=0, friendly_name=Yttergang, supported_features=17 @ 2019-11-27T19:08:19.244669+01:00>,

**Comment by Svellem** [comment]
@Heronimonimo 
Regarding recent changes I did was upgrading from 0.99.2 to 0.102.2 and upgrade HACS to the latest version. I have removed HACS, I have reverted to 0.99.2. Starting to regret not doing full backups now. and I will probably try a clean install if find no way to get to the source of this issue.

**Comment by Svellem** [comment]
Started from scratch, deleted all content of \config and the hidden \config\.storage folders and restarted the HASSIO folder. All good for now, but time will tell if somwhere in my devices og custom addons there still is an issue. when I rebuild with old config files

**Comment by Heronimonimo** [comment]
@Svellem I would do a search on 'nan' in your logs. This might point you to the sensor that gives the error.

@bramkragten I had a look at the code of the history sensor, but unfortunately I'm not fluent enough in Python to totally understand where the fix has to be made in the statistics sensor. It seems that a wrong value in the database is the cause of it. So I would think a filtering on NaN values on loading of the historical values would fix it.

**Comment by bramkragten** [comment]
Yes, adding a check here would do it:
<https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/statistics/sensor.py#L132>

**Comment by bramkragten** [comment]
But the question is what integration produces `NaN` to put in the recorder in the first place.

**Comment by iantrich** [comment]
@bramkragten close or transfer to backend to filter on history retrieval call?

**Comment by bramkragten** [comment]
It isn't a frontend problem, I would say close and the reporter can create a new issue for the integration that causes this.
