### ISSUE TITLE
Lovelace Thermostat card UI slider dot not showing correct when set to lowest temp

### ISSUE THREAD

**Issue by pinquin87** [home-assistant/home-assistant-polymer#4265]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
Home Assistant 0.102.1

**Last working Home Assistant release (if known):**
I think it was working correct on Home Assistant 0.102.0
I am sure it was working correct on Home Assistant 0.101.3

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Safari, Chrome and iOS App.
On iOS 13.1.3

On windows desktop (Chrome, Firefox and Edge) this issue is not there.

**Description of problem:**
The thermostat card does not show correct on mobile (test on iOS app, Safari and Chrome)
This issue only occurs when the thermostaat temperature slider is set to the lowest value, or set to away/eco mode.

Screenshot:
![Thermostat card issue](https://user-images.githubusercontent.com/43417732/69423474-7d47d780-0d26-11ea-84de-1fc90a1f41cb.jpg)

**Javascript errors shown in the web inspector (if applicable):**
-
```

```

**Additional information:**
-

**Comment by VDRainer** [comment]
Can confirm, same with the light card.
If light is off, the 'Handle' is big.
![20191122_12:47:49_001](https://user-images.githubusercontent.com/26381449/69423692-17a81b00-0d27-11ea-87db-5cc882f99c5e.png)

**Comment by 3ative** [comment]
Hmmm... It must be an IOS 'thing'

Looks _AOK_ on Android (Chrome)
![thermo](https://user-images.githubusercontent.com/51385971/69424125-c0527c80-0d1f-11ea-8db8-0384da4acdef.jpg)

**Comment by bramkragten** [comment]
@thomasloven

**Comment by thomasloven** [comment]
I'm aware. It's a problem with the component.
Will start debugging as soon as I get home.

**Comment by thomasloven** [comment]
It seems safari doesn't like arcs with no length...

**Comment by P-Verbrugge** [comment]
It seems fine in Firefox. I checked it there. So far I only see the problem in Safari on the Mac and on iOS.

**Comment by olddawgpowers** [comment]
Sorry, I am new to Home Assistant and github.  Does the closed mean it has been resolved or that a solution has been submitted and it will be corrected on next release?

**Comment by bramkragten** [comment]
@olddawgpowers it will be in 0.102.2

**Comment by tamet83** [comment]
Sorry but the problem still persist even with the latest update.
