### ISSUE TITLE
Pop up window scrolling bug

### ISSUE THREAD

**Issue by anrada73** [home-assistant/home-assistant-polymer#4884]
Home Assistant release with the issue: 0.105.4
Last working Home Assistant release (if known): Probably 0.105.3
Operating environment (Hass.io)

After the last update, the light card stopped displaying correctly and there is no way to change the lighting effects. https://share-your-photo.com/7ce77f03dd
https://www.youtube.com/watch?v=g3fcyyapPM4
Test with Mobil-Android and Windows- Chrome Browser

**Comment by DerFlob** [comment]
I see a similar issue on Linux with Firefox on a small screen, HA 105.4

The controls do not fit the screen height and are not scrollable.

Maybe relates to [PR #4774](https://github.com/home-assistant/home-assistant-polymer/pull/4774)? Which was introduced into HA at 105.1 (frontend: 20200130.2).

**Comment by anrada73** [comment]
0.105.3 - ok, 0.105.4- bug
https://www.youtube.com/watch?v=g3fcyyapPM4

**Comment by SylvainGa** [comment]
Yep, seeing this too. Can't scroll to change the lighting effects if the card doesn't fully fit on screen.

**Comment by dshokouhi** [comment]
FYI this bug impacts more than just the light card. It might impact any more info panel that needs scrolling.  The bottom of this screenshot looks pretty similar to the light card in bug.

![image](https://user-images.githubusercontent.com/1634145/75264263-05b19a80-57a4-11ea-8269-4f463a94606e.png)

**Comment by anrada73** [comment]
Yes, that's pop up window bug.

**Comment by bramkragten** [comment]
This should have been fixed with https://github.com/home-assistant/home-assistant-polymer/pull/4774.
I can't reproduce this locally.

**Comment by dshokouhi** [comment]
@bramkragten for me this issue started in 0.105 I have not updated to 0.106 to see if its better though. I think it only happens in desktop UI when the more info panel stretches.  So more info for light card with color wheel or zwave with all of the attributes.

**Comment by bramkragten** [comment]
It was in 0.105 but was fixed in a hotfix

**Comment by SylvainGa** [comment]
I'm at 0.106 and still present for me. Still can't scroll down on my android phone when there is more to show in the light card.

**Comment by anrada73** [comment]
with 0.106 ok. tnx.

**Comment by Mariusthvdb** [comment]
> It was in 0.105 but was fixed in a hotfix

which hot fix was that Bram? I am using 105.5 and see it all over the longer more-info's
<img width="429" alt="Schermafbeelding 2020-02-27 om 18 19 51" src="https://user-images.githubusercontent.com/33354141/75468699-e9715180-598d-11ea-9849-94f78ea1924e.png">

**Comment by dshokouhi** [comment]
@Mariusthvdb I was on 0.105.4, I actually skipped 0.105.5.  Just now updated to 0.106 and its fixed there.  I think the fix did not really make it into a hot fix but in 0.106.
