### ISSUE TITLE
Logbook scrolling non-fluid on 0.106 beta

### ISSUE THREAD

**Issue by olbjan** [home-assistant/home-assistant-polymer#4977]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Logbook scrolling on Safari on iOS and iOS app (Webkit) is non-fluid and only moves one line at a time.
This was supposedly fixed by #4950 but this was either non-successful or hasn't been merged yet.

## Expected behavior

Logbook scrolling should be fluid as any other ui interaction.

## Steps to reproduce

Open logbook

## Environment

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): 
- Browser and browser version: 
- Operating system: 

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

![20200225_080618000_iOS](https://user-images.githubusercontent.com/43749346/75227762-161b4280-57af-11ea-8e4c-206f8e8baac9.gif)

**Comment by olbjan** [comment]
Closing as has been fixed already and the PR just hasn't been merged yet.

**Comment by WilldabeastHA** [comment]
@olbjan I've installed dev version: 0.107.0.dev20200227 but still have the same logbook issue.

**Comment by bramkragten** [comment]
It is not in 0.107.0.dev yet. We have not updated the frontend.
