### ISSUE TITLE
0.106 broke entity-button, button is always off even if the state of the entity is on.

### ISSUE THREAD

**Issue by sblantipodi** [home-assistant/home-assistant-polymer#4994]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

entity-button does not show correct entity state anymore

as you can see here, both the entity (switch and input_boolean) are "on"

![wol](https://user-images.githubusercontent.com/4722227/75377476-37c11a80-58d2-11ea-955d-675c1b63d8c4.JPG)

![input](https://user-images.githubusercontent.com/4722227/75377484-3a237480-58d2-11ea-88e1-06d7f46f24fb.JPG)

but frontend does not show the correct state, the button is off.

![shot](https://user-images.githubusercontent.com/4722227/75377281-bff2f000-58d1-11ea-9851-2351b4852833.JPG)

same config worked like a charm on 0.105.5

## Expected behavior

entity button should be on or off based on the entity state.

## Steps to reproduce

simply create an entity button like the one shown in the description of the issue

## Environment

- Home Assistant release with the issue: 0.106
- Last working Home Assistant release (if known): 0.105.5
- UI Type (States or Lovelace):  LL
- Browser and browser version: FF and Chrome
- Operating system: Windows/Android

**Comment by iantrich** [comment]
Will be fixed in 0.106.1. For now you can set `state_color: true`

**Comment by iantrich** [comment]
Fixed in https://github.com/home-assistant/home-assistant-polymer/pull/4995

**Comment by sblantipodi** [comment]
@iantrich @bramkragten 
just updated to 0.106.1 but the issue still there. nothing fixed. please double check.

**Comment by sl33pyon3** [comment]
I can confirm @sblantipodi findings. It is still not working correctly and I have the same results using the HA app on Android.

**Comment by 4x4ff** [comment]
Same for me.  Still broken.

**Comment by iantrich** [comment]
0.106.1 didn't include a frontend release. 0.106.2 should, I believe

**Comment by bramkragten** [comment]
Yes, I was too slooowwww sorry

**Comment by sblantipodi** [comment]
Thanks for the answer guys. Keep up the good work.
Congratulations for your work!!!!!

**Comment by sl33pyon3** [comment]
I updated to 0.106.2 and I am now seeing the entity buttons changing state. Thank you very much!
