### ISSUE TITLE
History page not loading in Safari

### ISSUE THREAD

**Issue by neborkia** [home-assistant/home-assistant-polymer#791]
The data in the History menu is not displayed in Safari (macOS & iOS) and not in the iOS app.
It is still working with Firefox and Chrome.

**Comment by balloob** [comment]
This has been fixed in 0.60.1

**Comment by tomtaylor** [comment]
@balloob I think I'm still experiencing this on 0.61.1. Can you confirm this definitely made it into 0.61?

**Comment by balloob** [comment]
Yes, it has been fixed in 0.61. Make sure that you set your frontend to serve "auto" or "es5" version of the frontend.
